// Authenticate user action types
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

// User actions
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_ID_ERROR = 'GET_USER_BY_ID_ERROR';
export const GET_ALL_USER_EMAILS = 'GET_ALL_USER_EMAILS';
export const GET_ALL_USER_EMAILS_ERROR = 'GET_ALL_USER_EMAILS_ERROR';
export const GET_ALL_USER_USERNAMES = 'GET_ALL_USER_USERNAMES';
export const GET_ALL_USER_USERNAMES_ERROR = 'GET_ALL_USER_USERNAMES_ERROR';

// Team actions
export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_ALL_TEAMS_ERROR = 'GET_ALL_TEAMS_ERROR';
export const GET_ALL_PUBLIC_TEAMS = 'GET_ALL_PUBLIC_TEAMS';
export const GET_ALL_PUBLIC_TEAMS_ERROR = 'GET_ALL_PUBLIC_TEAMS_ERROR';
export const GET_ALL_PRIVATE_TEAMS = 'GET_ALL_PRIVATE_TEAMS';
export const GET_ALL_PRIVATE_TEAMS_ERROR = 'GET_ALL_PRIVATE_TEAMS_ERROR';
export const GET_TEAM_USERS = 'GET_TEAM_USERS';
export const GET_ALL_TEAMS_BY_EVENT_ID = 'GET_ALL_TEAMS_BY_EVENT_ID';
export const GET_ALL_TEAMS_BY_EVENT_ID_ERROR = 'GET_ALL_TEAMS_BY_EVENT_ID_ERROR';
export const ADD_TEAMS = 'ADD_TEAMS';
export const ADD_TEAMS_ERROR = 'ADD_TEAMS_ERROR';
export const ADD_USER_TO_TEAM = 'ADD_USER_TO_TEAM';
export const ADD_USER_TO_TEAM_ERROR = 'ADD_USER_TO_TEAM_ERROR';
export const DELETE_USER_FROM_TEAM = 'DELETE_USER_FROM_TEAM';
export const DELETE_USER_FROM_TEAM_ERROR = 'DELETE_USER_FROM_TEAM_ERROR';

// Event actions
export const ADD_EVENT = 'ADD_EVENT';
export const ADD_EVENT_ERROR = 'ADD_EVENT_ERROR';
export const EDIT_EVENT = 'EDIT_EVENT';
export const EDIT_EVENT_ERROR = 'EDIT_EVENT_ERROR';
export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';
export const GET_EVENT = 'GET_EVENT';
export const GET_EVENT_ERROR = 'GET_EVENT_ERROR';
export const JOIN_EVENT = 'JOIN_EVENT';
export const JOIN_EVENT_ERROR = 'JOIN_EVENT_ERROR';

// Log Actions
export const ADD_EXERCISE_LOG = 'ADD_EXERCISE_LOG';
export const ADD_EXERCISE_LOG_ERROR = 'ADD_EXERCISE_LOG_ERROR';
export const GET_TOTAL_USER_DISTANCE = 'GET_TOTAL_USER_DISTANCE';
export const GET_TOTAL_USER_DISTANCE_ERROR = 'GET_TOTAL_USER_DISTANCE_ERROR';

// Record Actions
export const GET_RECORDS = 'GET_RECORDS';
export const GET_RECORDS_ERROR = 'GET_RECORDS_ERROR';
export const ADD_RECORD = 'ADD_RECORD';
export const ADD_RECORD_ERROR = 'ADD_RECORD_ERROR';
export const DELETE_RECORD = 'DELETE_RECORD';
export const DELETE_RECORD_ERROR = 'DELETE_RECORD_ERROR';